### ISSUE TITLE
boundary bug?处理建筑区3d加上边界限制后输出区域结果很差. 3D model  of the building area is poor when with boundary constraints by pyodm

### ISSUE THREAD

**Issue by meiyanzhao** [OpenDroneMap/PyODM#30] opened 2024-06-28 09:21 UTC
### How did you install ODM? (Docker, installer, natively, ...)?
**install doker:**
docker run -dp 8888:3000 --gpus all  --name nodeodmgpu01 opendronemap/nodeodm:gpu

**in python:**
n = Node(ip, port)
boundary ={"type":"FeatureCollection","crs":{"type":"name","properties":{"name":"EPSG:4326"}},"features":[{"type":"Feature","id":0,"geometry":{"type":"Polygon","coordinates":[[[104.15728688732897,36.54148301442387],[ 104.15818386146158,36.54147661480294],[104.15818095611374,36.5411700324329],[104.15725376030238,36.54113720094068]]]}}]}
boundarystr = json.dumps(boundary,ensure_ascii=False)
task = n.create_task(images_name, {"3d-tiles": True,"boundary":boundarystr,"no-gpu":False})

**logs:**
[log.json](https://github.com/user-attachments/files/16027260/log.json)
[task_output.txt](https://github.com/user-attachments/files/16027264/task_output.txt)

**images:**
![DJI_20240213085228_0001_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/6df95efa-2248-4933-ad7c-6b0bdb3b03d9)
![DJI_20240213085238_0002_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/2ed0440a-4295-4c16-800a-634816207849)
![DJI_20240213085242_0003_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/08ba7ddd-4062-4061-ba91-e4cf46652635)
![DJI_20240213085246_0004_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/49be1d64-4401-4756-8b50-b149436d9c5d)
![DJI_20240213085250_0005_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/9b7fa8c8-2c20-403b-b50a-e0bd84e5410d)
![DJI_20240213085254_0006_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/10fb9712-0061-450d-a158-8fd92851c002)
![DJI_20240213085258_0007_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/7a9d4eaf-6cf4-4eb9-ba5d-0a1260509fc2)
![DJI_20240213085302_0008_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/f6cc1238-6df2-4a15-985b-d3a922794294)
![DJI_20240213085304_0009_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/cfcccb30-bb2f-491b-b394-2a61cfdbb242)
![DJI_20240213085308_0010_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/cadcfc30-08d5-4f14-bb75-3d55baccffe4)
![DJI_20240213085312_0011_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/72b95005-a4f9-403c-9077-f40cd318e486)
![DJI_20240213085316_0012_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/225a55f3-a4b9-44e0-b993-62d5e0663717)
![DJI_20240213085320_0013_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/d47eb4dc-5a55-4324-a298-c8a2bd9f5419)
![DJI_20240213085324_0014_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/591923cc-fb8a-43e9-90d0-ed45fe4c3735)
![DJI_20240213085328_0015_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/850785a9-6a4e-47b9-8b55-69930967bd63)
![DJI_20240213085332_0016_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/649ec02e-36ee-445f-a2d3-76c2ce3fe03a)
![DJI_20240213085336_0017_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/7b4f99a1-034d-4b3d-ace7-e6620a4624b0)
![DJI_20240213085340_0018_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/cd4610b8-9a12-4af3-8829-0b3440eca830)
![DJI_20240213085344_0019_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/818211ba-2570-4939-8ac9-4132cb67cc44)
![DJI_20240213085348_0020_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/f6b3d9c4-814b-40b1-8001-818143a4240a)
![DJI_20240213085352_0021_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/1ab0badf-c04c-4736-8a20-5562748ea242)
![DJI_20240213085356_0022_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/1456801d-a1cf-4be6-a580-4b126b7bf1e6)
![DJI_20240213085400_0023_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/1f66d8d1-98a8-4e9e-b868-e7c00b606056)
![DJI_20240213085406_0024_WIDE](https://github.com/OpenDroneMap/PyODM/assets/169761406/9fe08f1f-2d68-4440-a96a-d717d1101e7a)

[Type answer here]

### What is the problem?
When dealing with oblique photography models  of the building area with boundary constraints, the output model effect is very poor, the model is very rough, with many small holes, texture mapping errors at the boundaries, and is messy(as shown in Figure 1111). But without boundary constraints(if this parameter is not set:“boundary”:boundarystr), the effect of the central region of the model is still good(as shown in Figure 2222）.
![1111](https://github.com/OpenDroneMap/ODM/assets/169761406/4b43c78f-be34-42fe-a9ba-3bcd2de3c188)

![2222](https://github.com/OpenDroneMap/PyODM/assets/169761406/c9d089ad-9cf9-4d8c-a04a-034b62827a17)

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

I have checked the point cloud file and the data is quite good. However, there are loopholes and rough textures in the OBJ model results of the cropped area, which I believe may be a bug. the model with all region processing showed high point cloud density and good texture effect; The model using boundary restricted area processing has low point cloud density, sparse point clouds, and poor texture effects. Analyzing the reason, it should be that when processing the 3D model, the set boundaries were used to restrict the reconstruction area. However, in reality, the reconstruction area should not be restricted.  I think when dealing with oblique photography models with boundary constraints, the logic should be to first use all photos to reconstruct the entire area, and then output the model results for the range within the boundary area. But in reality, this is not the logic. When outputting the model, only part of the photos were used (according to the results, the texture at the boundary of the cropped model was based on the surrounding image texture, not the original overall texture position, resulting in a disordered texture), and the result was relatively rough without post-processing such as smoothing and hole filling. So it is necessary to optimize the development logic and perform post-processing on the cropping results.

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset AND task output log, uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

1. When using the boundary parameter to process oblique photography models of building areas, please confirm whether all photos were first used for model reconstruction, and then the boundary was used to crop the reconstruction results.
2. If so, check the odd_filterpoints process and see why using boundary results in sparse point cloud results, rough texture results, low accuracy, holes, and incorrect texture mapping around the model (using photos around the region boundary instead of actual photos at the local location).
3. If there are no issues with the above, please post-process the cropped 3D results: smooth, fill in holes, improve accuracy, crop excess models around, and make the trimmed edges neat.

**Comment by meiyanzhao** [comment] 2024-06-28 09:24
Figure 1111:
![1111](https://github.com/OpenDroneMap/PyODM/assets/169761406/971b600c-2216-4e05-b0d9-da625252be1d)

Figure 2222:
![2222](https://github.com/OpenDroneMap/PyODM/assets/169761406/765d21c5-19a7-4b1c-a9d5-2ed8aeb6d4f9)

**Comment by meiyanzhao** [comment] 2024-06-28 09:32
This is the result of my oblique photography using other photos, and the effect is the same as above. When  dealing with oblique photography models with boundary constraints, the output model effect is very poor, the model is very rough, with many small holes, texture mapping errors at the boundaries, and is messy(as shown in the first three images). But without boundary constraints(if this parameter is not set:“boundary”:boundarystr), the effect of the central region of the model is still good(as shown in the last image）.

![1](https://github.com/OpenDroneMap/PyODM/assets/169761406/5224305d-04ab-4991-8c0a-ed288e1f164f)
![2](https://github.com/OpenDroneMap/PyODM/assets/169761406/e8ac5f70-c2d4-4643-b4d5-4b3311e4069f)
![3](https://github.com/OpenDroneMap/PyODM/assets/169761406/3e1c9c76-a96c-4edf-a32e-99125049ce4a)

![4](https://github.com/OpenDroneMap/PyODM/assets/169761406/2f9a9906-a4f8-4572-8866-459bfd767d91)

**Comment by pierotofy** [comment] 2024-06-28 13:22
Duplicate of https://github.com/OpenDroneMap/ODM/issues/1769

**Closed as completed by pierotofy** 2024-06-28 13:22 UTC
